name: Build Image and Push Registry

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
      NEXT_PUBLIC_GA_ID: ${{ secrets.NEXT_PUBLIC_GA_ID }}
      BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
      BREVO_LIST_ID: ${{ secrets.BREVO_LIST_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Inject GA ID into .env
        run: |
          echo "NEXT_PUBLIC_GA_ID=$NEXT_PUBLIC_GA_ID" > .env
          echo "BREVO_API_KEY=$BREVO_API_KEY" > .env
          echo "BREVO_LIST_ID=$BREVO_LIST_ID" > .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: docker build -t $REGISTRY_NAME/mds-poc .

      - name: Log in to Docker Registry
        run: echo $REGISTRY_PASSWORD | docker login $REGISTRY_NAME -u $REGISTRY_USERNAME --password-stdin

      - name: Push Docker Image
        run: docker push $REGISTRY_NAME/mds-poc
