name: Deploy to VPS

on:
  workflow_run:
    workflows: ["Build Image and Push Registry"]
    types:
      - completed

env:
  IMAGE_NAME: mdsu-app

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      VPS_USER: ${{ secrets.VPS_USER }}
      VPS_IP: ${{ secrets.VPS_IP }}
      VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH for VPS
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ env.VPS_SSH_KEY }}

      - name: Add VPS to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan $VPS_IP >> ~/.ssh/known_hosts

      - name: SSH into VPS and deploy
        run: |
          ssh $VPS_USER@$VPS_IP << 'EOF'
            set -e
            echo "--Start pulling image--"
            sudo docker pull $REGISTRY_NAME/${IMAGE_NAME}:latest
            echo "--End pulling image--"
            sudo docker stop ${IMAGE_NAME}-container || true
            sudo docker rm ${IMAGE_NAME}-container || true
            echo "--Running container--"
            sudo docker run -d --name ${IMAGE_NAME}-container -p 3000:3000 $REGISTRY_NAME/${IMAGE_NAME}:latest
          EOF
