name: Deploy to VPS

on:
  workflow_run:
    workflows: ["Build Image and Push Registry"]
    types:
      - completed

env:
  IMAGE_NAME: mdsu-app

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      VPS_USER: ${{ secrets.VPS_USER }}
      VPS_IP: ${{ secrets.VPS_IP }}
      VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
      VPS_SSH_PASSPHRASE: ${{ secrets.VPS_SSH_PASSPHRASE }}
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.VPS_IP }}
          username: ${{ env.VPS_USER }}
          key: ${{ env.VPS_SSH_KEY }}
          passphrase: ${{ env.VPS_SSH_PASSPHRASE }}
          script: |
            set -e
            echo "--Start pulling image--"
            sudo docker pull $REGISTRY_NAME/${IMAGE_NAME}:latest
            echo "--End pulling image--"
            sudo docker stop ${IMAGE_NAME}-container || true
            sudo docker rm ${IMAGE_NAME}-container || true
            echo "--Running container--"
            sudo docker run -d --name ${IMAGE_NAME}-container -p 3000:3000 $REGISTRY_NAME/${IMAGE_NAME}:latest
